name: Scheduled Build for Notion Update

on:
  schedule:
    # GitHub ActionsはUTC（協定世界時）で動くため、日本時間から9時間引いた時間を設定します
    # 00:00 UTC = 09:00 JST
    # 09:00 UTC = 18:00 JST
    - cron: '0 0,9 * * *'
  workflow_dispatch: # これを入れておくと、GitHubの画面から「今すぐ更新」ボタンが押せます

jobs:
  build_request:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Amplify Build
        run: |
          curl -X POST -d {} "${{ secrets.AMPLIFY_WEBHOOK_URL }}" -H "Content-Type:application/json"